{{- if .Values.persistence.thumbnails.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-thumbnails
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - {{ .Values.persistence.thumbnails.accessMode }}
  {{- if .Values.persistence.thumbnails.storageClass }}
  storageClassName: {{ .Values.persistence.thumbnails.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.thumbnails.size }}
{{- end }}
