{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
---
{{- end }}
{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
---
{{- end }}
{{- if .Values.aspire.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-aspire
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: aspire
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.aspire.ports.ui }}
      targetPort: ui
      protocol: TCP
      name: ui
    - port: {{ .Values.aspire.ports.otlp }}
      targetPort: otlp
      protocol: TCP
      name: otlp
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: aspire
{{- end }}
