apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: photos-index

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - aspire-dashboard.yaml
  - api.yaml
  - indexing-service.yaml
  - cleaner-service.yaml
  - web.yaml
