apiVersion: v1
kind: Secret
metadata:
  name: photos-index-secrets
  namespace: photos-index
type: Opaque
stringData:
  POSTGRES_PASSWORD: "photospass"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=photosindex;Username=photosuser;Password=photospass"
